# Generated by Django 3.2.9 on 2021-12-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_managment_app', '0002_auto_20211228_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
