# Generated by Django 3.2.9 on 2021-12-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_managment_app', '0004_classname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
