# Generated by Django 3.2.9 on 2021-12-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_managment_app', '0006_myclassname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclassname',
            name='teacher_id',
        ),
    ]
