# Generated by Django 3.2.9 on 2021-12-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_managment_app', '0007_remove_myclassname_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_name_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_managment_app.myclassname')),
            ],
        ),
    ]
