# Generated by Django 3.2.9 on 2021-12-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('student_managment_app', '0008_sectionname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('full_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_name_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_managment_app.myclassname')),
                ('section_name_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_managment_app.sectionname')),
                ('teacher_name_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.teacher')),
            ],
        ),
    ]
